# Generated by Django 5.0 on 2024-01-23 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='movies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('cast', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('budget', models.IntegerField()),
                ('collection', models.IntegerField()),
                ('streaming', models.CharField(max_length=100)),
                ('rating', models.IntegerField()),
            ],
        ),
    ]
